AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CostQ - IAM Role Integration Template

  This template creates an IAM Role for CostQ platform to access your AWS account using temporary credentials.

  Permissions:
  1. ReadOnlyAccess(AWS ManagedPolicy)- Read-only access to all AWS services
  2. refresh-sp-recommendations(CustomPolicy)- Start Savings Plans recommendation generation

  Security features:
  - Temporary credentials (auto-expire in 15min-12hrs)
  - External ID (prevents confused deputy attacks)
  - Least privilege principle (read-only + single write operation)

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "CostQ Platform Configuration"
        Parameters:
          - CostQPlatformAccountId
          - ExternalId
      - Label:
          default: "Role Configuration"
        Parameters:
          - RoleName
          - SessionDuration
    ParameterLabels:
      CostQPlatformAccountId:
        default: "CostQ platform AWS Account ID"
      ExternalId:
        default: "External ID(Security Key)"
      RoleName:
        default: "IAM Role name"
      SessionDuration:
        default: "Session Duration(seconds)"

Parameters:
  CostQPlatformAccountId:
    Type: String
    Description: "CostQ platform AWS account ID (provided by CostQ)"
    AllowedPattern: '^\d{12}$'
    ConstraintDescription: "Must be 12 digits"
    Default: "000451883532"  # 🔧 TODO: Replace with actualplatformAccount ID

  ExternalId:
    Type: String
    Description: "External ID (auto-generated by CostQ platform)"
    MinLength: 16
    MaxLength: 128
    NoEcho: false  # No need to hide，External ID not a secret
    Default: "REPLACE_WITH_YOUR_EXTERNAL_ID"  # 🔧 Auto-filled by frontend

  RoleName:
    Type: String
    Description: "IAM Role name (recommended to keep default)"
    Default: "CostQRole"
    AllowedPattern: '^[\w+=,.@-]{1,64}$'
    ConstraintDescription: "Role name can only contain letters, numbers and +=,.@- characters, length 1-64"

  SessionDuration:
    Type: Number
    Description: "Temporary credential validity period(seconds)，Range 900-43200"
    Default: 3600
    MinValue: 900
    MaxValue: 43200

Resources:
  # CustomPolicy：Savings Plans recommendation generation
  RefreshSPRecommendationsPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${RoleName}-RefreshSPRecommendations"
      Description: "Allow CostQ start Savings Plans purchaserecommendation generationtask"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowSavingsPlansRecommendationGeneration
            Effect: Allow
            Action:
              - ce:StartSavingsPlansPurchaseRecommendationGeneration
            Resource: '*'
            # Note:
            # - This operation will not auto-purchase Savings Plans
            # - Only generates recommendation reports, final purchase decision controlled by you
            # - Recommendation reports help optimize costs

  # IAM Role：Trust CostQ platformaccount
  CostQIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      Description: "CostQ integration role - ReadOnlyAccess + SP recommendations"
      MaxSessionDuration: !Ref SessionDuration
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCostQPlatformAssumeRole
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${CostQPlatformAccountId}:root"
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Ref ExternalId
      ManagedPolicyArns:
        # AWS ManagedPolicy：Read-only access to all services
        - arn:aws:iam::aws:policy/ReadOnlyAccess
        # CustomPolicy：SP recommendation generation
        - !Ref RefreshSPRecommendationsPolicy
      Tags:
        - Key: Purpose
          Value: CostQIntegration
        - Key: Platform
          Value: CostQ
        - Key: ManagedBy
          Value: CloudFormation
        - Key: StackName
          Value: !Ref AWS::StackName

Outputs:
  RoleArn:
    Description: "IAM Role ARN - Copy this and paste into CostQ platform"
    Value: !GetAtt CostQIAMRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-RoleArn"

Metadata:
  # Template version info
  Version: 1.0.0
  LastUpdated: 2025-10-30
  Author: CostQ Team

  # License
  License: MIT

  # Changelog
  ChangeLog: |
    v1.0.0 (2025-10-30):
    - Initial version
    - Use ReadOnlyAccess managed policy
    - Add refresh-sp-recommendations custom policy
    - Support External ID security verification
    - Configurable session duration
